app = "${NAME}-lemmy"
primary_region = "${REGION}"

[build]
  dockerfile = "../docker/Dockerfile.lemmy"

[env]
  RUST_LOG = "warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
  RUST_BACKTRACE = "full"
