app = "${NAME}-pictrs"
primary_region = "${REGION}"

[build]
  image = "asonix/pictrs:0.4.0-rc.9"

[env]
  RUST_BACKTRACE = "full"
  PICTRS__SERVER__ADDRESS = "[::]:8080"
  PICTRS__SERVER__API__KEY = "${PICTRS_API_KEY}"
  PICTRS__MEDIA__VIDEO_CODEC = "vp9"
  PICTRS__MEDIA__GIF__MAX_WIDTH = "256"
  PICTRS__MEDIA__GIF__MAX_HEIGHT = "256"
  PICTRS__MEDIA__GIF__MAX_AREA = "65536"
  PICTRS__MEDIA__GIF__MAX_FRAME_COUNT = "400"

[mounts]
  source = "pictrs_data"
  destination = "/mnt"
